function run_summary(output)

sim_time      = output.simulationparams.sim_time;
dt            = output.simulationparams.dt;
use_damping   = output.simulationparams.damping.use_damping;
% num_it        = output.simulationparams.num_it;
num_it = 1;
max_s_element = output.simulationparams.max_s_element;
min_s_element = output.simulationparams.min_s_element;
wall_c_time   = output.simulationparams.totaltime;
sim_name      = output.simulationparams.sim_name;
num_s_layers  = size(output.simulationparams.soil_layers,1);
input_file    = output.simulationparams.input_acceleration;
max_value_acc = output.simulationparams.max_value_acc;
tdate         = date;

fileID = fopen('simulation_results/run_summary.txt','a');
fprintf(fileID,'%s%s%2.3f%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s\n',...
              tdate,...
              '  s-time: ',sim_time,...
              '  dt: ',num2str(dt),...
              '  Damping: ',num2str(use_damping),...
              '  MaxEsize: ',num2str(max_s_element),...
              '  MinEsize: ',num2str(min_s_element),...
              '  Num soil Layers: ', num2str(num_s_layers),...
              '  N_Iteration: ',num2str(num_it),...
              '  Time for it (s): ', num2str(wall_c_time),...
              '  Simulation Name: ',sim_name,...
              '  Input file name: ',input_file,...
              '  Max value of Input:', num2str(max_value_acc));
fclose(fileID);


end